# Generated by Django 3.2.8 on 2021-10-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.URLField(max_length=350, verbose_name='image'),
        ),
    ]
