version: '3.9'
services:
  backend:
    container_name: social_network_api
    build:
      context: .
    volumes:
      - .:/backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"